<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="google-site-verification" content="CAJSXz1q9IoKgvnzjtqfn7KaJhAJMC9sCywfxWYum7s" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Python Exceptions</title>
<meta name="description" content="In Python, exceptions are events that occur during the execution of a program that disrupt the normal flow of the program's instructions.">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
<link rel="canonical" href="https://www.devbabu.com/shorts/python/python-exceptions.html">
<link rel="icon" href="https://cdn.jsdelivr.net/gh/chandan-tudu/shorts@latest/assets/favicon.png" sizes="32x32" />
<link rel="icon" href="https://cdn.jsdelivr.net/gh/chandan-tudu/shorts@latest/assets/favicon.png" sizes="192x192" />
<link rel="apple-touch-icon" href="https://cdn.jsdelivr.net/gh/chandan-tudu/shorts@latest/assets/favicon.png" />
<meta name="msapplication-TileImage" content="https://cdn.jsdelivr.net/gh/chandan-tudu/shorts@latest/assets/favicon.png" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/chandan-tudu/shorts@latest/assets/style.min.css" />
</head>
<body>
<header class="header">
    <div class="wrap d-flex">
        <div class="logo">
            <a href="https://www.devbabu.com">DevBabu.Com</a>
        </div>
        <div class="right-action d-flex">
            <div class="search">
                <form action="/" method="GET" class="d-flex">
                    <input class="s-input" type="text" name="s" placeholder="Search..." autocomplete="off" required />
                    <button class="s-btn" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11ZM2 9a7 7 0 1 1 12.452 4.391l3.328 3.329a.75.75 0 1 1-1.06 1.06l-3.329-3.328A7 7 0 0 1 2 9Z" clip-rule="evenodd" />
                        </svg>
                    </button>
                </form>
            </div>
            <div class="theme">
                <button class="theme-btn">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="theme-moon">
                        <path fill-rule="evenodd" d="M7.455 2.004a.75.75 0 0 1 .26.77 7 7 0 0 0 9.958 7.967.75.75 0 0 1 1.067.853A8.5 8.5 0 1 1 6.647 1.921a.75.75 0 0 1 .808.083Z" clip-rule="evenodd" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="theme-sun">
                        <path d="M10 2a.75.75 0 0 1 .75.75v1.5a.75.75 0 0 1-1.5 0v-1.5A.75.75 0 0 1 10 2ZM10 15a.75.75 0 0 1 .75.75v1.5a.75.75 0 0 1-1.5 0v-1.5A.75.75 0 0 1 10 15ZM10 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6ZM15.657 5.404a.75.75 0 1 0-1.06-1.06l-1.061 1.06a.75.75 0 0 0 1.06 1.06l1.06-1.06ZM6.464 14.596a.75.75 0 1 0-1.06-1.06l-1.06 1.06a.75.75 0 0 0 1.06 1.06l1.06-1.06ZM18 10a.75.75 0 0 1-.75.75h-1.5a.75.75 0 0 1 0-1.5h1.5A.75.75 0 0 1 18 10ZM5 10a.75.75 0 0 1-.75.75h-1.5a.75.75 0 0 1 0-1.5h1.5A.75.75 0 0 1 5 10ZM14.596 15.657a.75.75 0 0 0 1.06-1.06l-1.06-1.061a.75.75 0 1 0-1.06 1.06l1.06 1.06ZM5.404 6.464a.75.75 0 0 0 1.06-1.06l-1.06-1.06a.75.75 0 1 0-1.061 1.06l1.06 1.06Z" />
                    </svg>
                </button>
            </div>
        </div>
    </div>
</header>
<div class="container">
<nav class="navigation">
<ul>
<li><a href="/">Home</a></li>
<li><a href="/shorts/index.html">Shorts</a></li>
<li><a href="./index.html">PYTHON</a></li>
</ul>
</nav>
<article>
<h1>Python Exceptions</h1><p>In Python, <strong>exceptions are events</strong> that <strong>occur during the execution of a program</strong> that <strong>disrupt the normal flow of the program's instructions</strong>.</p>

<p><strong>When an exceptional situation arises, an exception object is raised</strong>, and <strong>the normal flow of the program is interrupted</strong>. To handle exceptions, you use a mechanism called "exception handling."</p>

<p>Here's a basic overview of how exception handling works in Python:</p>

<h3 id="the-try-except-block-">The <code>try</code>, <code>except</code> Block:</h3>

<p>You use <strong>the <code>try</code> and <code>except</code> blocks to handle exceptions</strong>. Code that might raise an exception is placed inside the <code>try</code> block, and the handling of the exception is specified in the <code>except</code> block.</p>

<pre class="language-python"><code>try:
    # Code that might raise an exception
    result = 10 / 0  # This will raise a ZeroDivisionError
except ZeroDivisionError:
    # Code to handle the exception
    print("Error: Division by zero")
</code></pre>

<h3 id="handling-multiple-exceptions-">Handling Multiple Exceptions:</h3>

<p>You can handle multiple exceptions by providing multiple <code>except</code> blocks.</p>

<pre class="language-python"><code>try:
    value = int(input("Enter a number: "))
    result = 10 / value
except ZeroDivisionError:
    print("Error: Division by zero")
except ValueError:
    print("Error: Invalid input. Please enter a number.")
</code></pre>

<h3 id="the-else-and-finally-blocks-">The <code>else</code> and <code>finally</code> Blocks:</h3>

<ul>
<li>The <code>else</code> block is executed if no exceptions are raised in the <code>try</code> block.</li>
</ul>

<pre class="language-python"><code>try:
    result = 10 / 2
except ZeroDivisionError:
    print("Error: Division by zero")
else:
    print("Result:", result)
</code></pre>

<ul>
<li>The <code>finally</code> block is executed no matter what, whether an exception occurred or not. It is often used for cleanup operations.</li>
</ul>

<pre class="language-python"><code>try:
    value = int(input("Enter a number: "))
    result = 10 / value
except ZeroDivisionError:
    print("Error: Division by zero")
finally:
    print("This will be executed no matter what.")
</code></pre>

<h3 id="raising-exceptions-">Raising Exceptions:</h3>

<p>You can also explicitly raise exceptions using the <code>raise</code> statement.</p>

<pre class="language-python"><code>def example_function(value):
    if value &lt; 0:
        raise ValueError("Value must be non-negative")
    return value * 2

try:
    result = example_function(-5)
except ValueError as e:
    print(f"Caught an exception: {e}")
</code></pre>

<p>Understanding and handling exceptions is crucial for writing robust and reliable Python programs. It allows you to gracefully handle errors and prevent unexpected crashes.</p>
</article>
</div>
<footer>
    <ul class="footer-nav d-flex">
        <li><a href="/about-us/">About</a></li>
        <li><a href="/privacy-policy/">Privacy</a></li>
        <li><a href="/contact-us/">Contact</a></li>
    </ul>
    <div class="extra" id="extraEl"></div>
</footer>
<script src="https://cdn.jsdelivr.net/gh/chandan-tudu/shorts@latest/assets/script.min.js"></script>
</body>
</html>